<?php

if( function_exists('register_field_group') ):

register_field_group(array (
	'key' => 'group_53c9629e993a4',
	'title' => 'Calculator',
	'fields' => array (
		array (
			'key' => 'field_53d27e4de4405',
			'label' => 'Year',
			'name' => 'year',
			'prefix' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'min' => '',
			'max' => '',
			'layout' => 'row',
			'button_label' => 'Add Year',
			'sub_fields' => array (
				array (
					'key' => 'field_53d27e8633733',
					'label' => 'Year',
					'name' => 'title',
					'prefix' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'column_width' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_53d113f5d603e',
					'label' => 'Cost',
					'name' => 'costs',
					'prefix' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'column_width' => '',
					'min' => '',
					'max' => '',
					'layout' => 'row',
					'button_label' => 'Add Cost',
					'sub_fields' => array (
						array (
							'key' => 'field_53d114b5d6042',
							'label' => 'Name',
							'name' => 'name',
							'prefix' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_53d1142dd603f',
							'label' => 'Expense',
							'name' => 'expense',
							'prefix' => '',
							'type' => 'number',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '',
							'max' => '',
							'step' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_53d1342653976',
							'label' => 'Editable?',
							'name' => 'editable',
							'prefix' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'column_width' => '',
							'message' => '',
							'default_value' => 0,
						),
						array (
							'key' => 'field_53f371550722b',
							'label' => 'Editable Fields',
							'name' => 'editable_fields',
							'prefix' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_53d1342653976',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'column_width' => '',
							'min' => '',
							'max' => '',
							'layout' => 'table',
							'button_label' => 'Add Field',
							'sub_fields' => array (
								array (
									'key' => 'field_53f371690722c',
									'label' => 'Name',
									'name' => 'name',
									'prefix' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'column_width' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
					),
				),
				array (
					'key' => 'field_53ff7211b6d99',
					'label' => 'Summer',
					'name' => 'summer',
					'prefix' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'column_width' => '',
					'min' => '',
					'max' => '',
					'layout' => 'row',
					'button_label' => 'Add Cost',
					'sub_fields' => array (
						array (
							'key' => 'field_53ff74a1b6d9a',
							'label' => 'Name',
							'name' => 'name',
							'prefix' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_53ff74aeb6d9b',
							'label' => 'Expense',
							'name' => 'expense',
							'prefix' => '',
							'type' => 'number',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '',
							'max' => '',
							'step' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_53ff74e8b6d9c',
							'label' => 'Editable?',
							'name' => 'editable',
							'prefix' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'column_width' => '',
							'message' => '',
							'default_value' => 0,
						),
						array (
							'key' => 'field_53ff74feb6d9d',
							'label' => 'Editable Fields',
							'name' => 'editable_fields',
							'prefix' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_53ff74e8b6d9c',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'column_width' => '',
							'min' => '',
							'max' => '',
							'layout' => 'table',
							'button_label' => 'Add Field',
							'sub_fields' => array (
								array (
									'key' => 'field_53ff7529b6d9e',
									'label' => 'Name',
									'name' => 'name',
									'prefix' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'column_width' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
					),
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'calculator',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

endif;